name: SlimeWorldManager
version: ${project.version}
main: com.grinderwolf.swm.plugin.SWMPlugin
author: Grinderwolf
description: Slime World Manager is a resource that implements the Slime Region Format, designed by the Hypixel Team to load and save worlds more efficiently.
api-version: 1.13
commands:
  swm:
    description: Main SWM command.
    usage: /swm <cmd>